name: crpropa-example-test
on: [push, pull_request]

jobs:
  linux:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
         - name: "ubuntu-20"
           os: ubuntu-20.04
           cxx: "g++-9"
           cc: "gcc-9"
           fc: "gfortran-9"
           swig_builtin: "Off" #uses swig 4.0.1
           py: "/usr/bin/python3" #python 3.8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Preinstall
        run: |
          sudo apt-get update
          sudo apt-get install libmuparser-dev python3-dev python-dev python3-numpy python-numpy python3-setuptools python-setuptools libhdf5-serial-dev libomp5 libomp-dev libfftw3-dev libcfitsio-dev lcov
          pip3 install jupyter
          pip3 install --upgrade Pygments
      - name: Set up the build
        env:
          CXX: ${{ matrix.config.cxx }}
          CC: ${{ matrix.config.cc }}
          FC: ${{ matrix.config.fc }}
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local -DENABLE_PYTHON=True -DPYTHON_EXECUTABLE=${{ matrix.config.py }} -DENABLE_TESTING=Off -DENABLE_SWIG_BUILTIN=${{ matrix.config.swig_builtin }} -DSIMD_EXTENSIONS=native
      - name: Build CRPropa
        run: |
          cd build
          make install -j
      - name: convert notebooks to python 
        env: 
          PYTHONPATH: "$/home/runner/.local/lib/python3.8/site-packages/"
          runfolder: "notebook_run"
        run: |
          mkdir "$runfolder"
          for file in doc/pages/example_notebooks/*/*.ipynb; do
            if [ -f "$file" ]; then
              jupyter-nbconvert --to python "$file" --output-dir "$runfolder" --RegexRemovePreprocessor.patterns="^%"
            fi
          done
      - name: run all python scripts
        env: 
          PYTHONPATH: "$/home/runner/.local/lib/python3.8/site-packages/"
          runfolder: "notebook_run"
        run: | 
          cd "$runfolder"
          python3 -c "from sys import path; print(path)"
          python3 -c "from crpropa import c_light"
          for file in ./*.py; do 
            if [ -f "$file" ]; then
              python3 "$file"
            fi
          done              
          
